#!/usr/bin/env bash

# Update autograder files

. /autograder/source/env.sh
. /autograder/source/envVars.sh

echo \$REPO_NAME=${REPO_NAME}
pwd
cd /autograder/git-repo/${REPO_NAME}
pwd
git pull origin master
chmod u+x ./grade.sh
./grade.sh


